# Bank Customer Churn Prediction
### Artificial Neural Networks

## Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import sys

In [2]:
tf.__version__

'2.6.0'

# 1) Data Preprocessing

## Importing dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3 : -1].values
y = dataset.iloc[:, -1].values

In [5]:
np.set_printoptions(threshold=sys.maxsize)

In [7]:
print(X[:10])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]]


In [8]:
print(y[:10])

[1 0 1 0 0 1 0 1 0 0]


## Encoding categorical data

Label Encoding the "Gender" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [10]:
print(X[:10])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 1 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 1 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 0 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 1 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 1 27 2 134603.88 1 1 1 71725.73]]


One Hot Encoding the "Geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X[:10])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1 79084.1]
 [0.0 0.0 1.0 645 1 44 8 113755.78 2 1 0 149756.71]
 [1.0 0.0 0.0 822 1 50 7 0.0 2 1 1 10062.8]
 [0.0 1.0 0.0 376 0 29 4 115046.74 4 1 0 119346.88]
 [1.0 0.0 0.0 501 1 44 4 142051.07 2 0 1 74940.5]
 [1.0 0.0 0.0 684 1 27 2 134603.88 1 1 1 71725.73]]


### Splitting the dataset into Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 2) Building the ANN

## Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

## Adding the input layer and first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# 3) Training the ANN

## Compiling the ANN

In [19]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Training the ANN on the Training set

In [20]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 533us/step - loss: 0.5792 - accuracy: 0.7354
Epoch 2/100
250/250 [==============================] - 0s 521us/step - loss: 0.4697 - accuracy: 0.7995
Epoch 3/100
250/250 [==============================] - 0s 493us/step - loss: 0.4390 - accuracy: 0.8036
Epoch 4/100
250/250 [==============================] - 0s 505us/step - loss: 0.4227 - accuracy: 0.8098
Epoch 5/100
250/250 [==============================] - 0s 517us/step - loss: 0.4095 - accuracy: 0.8145
Epoch 6/100
250/250 [==============================] - 0s 493us/step - loss: 0.3980 - accuracy: 0.8225
Epoch 7/100
250/250 [==============================] - 0s 497us/step - loss: 0.3882 - accuracy: 0.8284
Epoch 8/100
250/250 [==============================] - 0s 489us/step - loss: 0.3805 - accuracy: 0.8355
Epoch 9/100
250/250 [==============================] - 0s 493us/step - loss: 0.3746 - accuracy: 0.8401
Epoch 10/100
250/250 [==============================] - 0s 509us/step - l

250/250 [==============================] - 0s 493us/step - loss: 0.3397 - accuracy: 0.8616
Epoch 80/100
250/250 [==============================] - 0s 493us/step - loss: 0.3398 - accuracy: 0.8625
Epoch 81/100
250/250 [==============================] - 0s 505us/step - loss: 0.3397 - accuracy: 0.8629
Epoch 82/100
250/250 [==============================] - 0s 521us/step - loss: 0.3396 - accuracy: 0.8629
Epoch 83/100
250/250 [==============================] - 0s 497us/step - loss: 0.3399 - accuracy: 0.8612
Epoch 84/100
250/250 [==============================] - 0s 549us/step - loss: 0.3390 - accuracy: 0.8622
Epoch 85/100
250/250 [==============================] - 0s 509us/step - loss: 0.3394 - accuracy: 0.8630
Epoch 86/100
250/250 [==============================] - 0s 513us/step - loss: 0.3391 - accuracy: 0.8630
Epoch 87/100
250/250 [==============================] - 0s 517us/step - loss: 0.3392 - accuracy: 0.8635
Epoch 88/100
250/250 [==============================] - 0s 505us/step - loss:

# 4) Making the predictions and evaluating the model

## Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, Will the customer leave the bank?

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


## Predicting the test set results

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)[:20])

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 204  201]]


0.859